#!/usr/bin/env python3
"""Map battle-overlay D_* symbols onto guest RAM for the native port.

Matching still uses the externs.  Under XENO_PC_PORT, overlay-range arrays
and scalars become PSX_ADDR aliases so decompiled C writes the loaded
battle.bin image instead of a second host copy.  Pointer-typed overlay
symbols load the guest word and translate that too.
"""
from __future__ import annotations

import re
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BATTLE_SRC = ROOT / "src" / "battle"
HEADER = ROOT / "pc_port" / "src" / "battle_overlay_guest_ram.h"
CANDIDATES = ROOT / "pc_port" / "src" / "battle_overlay_host_leaf_candidates.inc"
OVERLAY_LO = 0x8006FAF0
OVERLAY_HI = 0x800E0000

EXTERN_RE = re.compile(r"^extern\s+([^;]+);", re.M)
FUNC_RE = re.compile(
    r"(?:__attribute__\(\(weak\)\)\s*)*(?:static\s+)?"
    r"(?:void|u32|s32|int|long|short|u16|s16|u8|s8|char|u32\s+\*|void\s+\*|"
    r"u8\s+\*|s16\s+\*|u16\s+\*)\s+(func_\w+)\s*\(([^)]*)\)\s*\{",
    re.S,
)
CALL_RE = re.compile(
    r"\b(func_\w+|SetSemiTrans|SetShadeTex|LoadImage|DrawSync|HeapAlloc|"
    r"HeapFree|Archive\w+|WorkList\w+|TimerWorkList\w+|rand|ratan2|rcos|"
    r"rsin|GetTPage|GetClut)\s*\("
)
NESTED_RE = re.compile(
    r"\*\(\s*(?:u8|u16|u32|s16|s32|void)\s*\*\s*\)\s*\(\s*\*\s*\(\s*u32\s*\*\s*\)"
    r"|\*\(\s*u8\s*\*\*\s*\)"
    r"|u8\s*\*\*"
)


def overlay_addr(name: str) -> int | None:
    if not re.match(r"D_8[0-9A-Fa-f]{7}$", name):
        return None
    value = int(name[2:], 16)
    if OVERLAY_LO <= value < OVERLAY_HI:
        return value
    return None


def parse_extern(raw: str) -> tuple[str, str] | None:
    raw = re.sub(r"\s+", " ", raw).strip()
    names = re.findall(r"\b(D_\w+)\b", raw)
    if not names:
        return None
    name = names[-1]
    if overlay_addr(name) is None:
        return None
    before = raw.split(name)[0]
    if "*" in before:
        kind = "ptr"
    elif "[]" in raw:
        kind = "array"
    else:
        kind = "scalar"
    type_tok = before.replace("const", "").replace("*", " ").strip().split()[-1]
    return name, kind, type_tok


def extract_body(text: str, brace: int) -> str:
    depth = 0
    for j, ch in enumerate(text[brace:], brace):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[brace + 1 : j]
    return ""


def collect_decls() -> OrderedDict:
    decls: OrderedDict[str, tuple[str, str]] = OrderedDict()
    for path in sorted(BATTLE_SRC.glob("*.c")):
        text = path.read_text(errors="ignore")
        for match in EXTERN_RE.finditer(text):
            parsed = parse_extern(match.group(1))
            if parsed is None:
                continue
            name, kind, type_tok = parsed
            rank = {"scalar": 0, "array": 1, "ptr": 2}
            old = decls.get(name)
            if old is None or rank[kind] > rank[old[0]]:
                decls[name] = (kind, type_tok)
    return decls


def wrap_externs(names: set[str]) -> int:
    changed = 0
    for path in sorted(BATTLE_SRC.glob("*.c")):
        text = path.read_text()
        original = text

        def repl(match: re.Match) -> str:
            line = match.group(0)
            parsed = parse_extern(match.group(1))
            if parsed is None or parsed[0] not in names:
                return line
            if line.strip().startswith("#"):
                return line
            return f"#ifndef XENO_PC_PORT\n{line}\n#endif"

        # Only wrap standalone extern lines that are not already guarded.
        lines = text.splitlines(keepends=True)
        out = []
        i = 0
        while i < len(lines):
            line = lines[i]
            stripped = line.strip()
            m = re.match(r"extern\s+([^;]+);", stripped)
            if (
                m
                and i > 0
                and lines[i - 1].strip() == "#ifndef XENO_PC_PORT"
            ):
                out.append(line)
                i += 1
                continue
            parsed = parse_extern(m.group(1)) if m else None
            if parsed and parsed[0] in names:
                out.append("#ifndef XENO_PC_PORT\n")
                out.append(line if line.endswith("\n") else line + "\n")
                out.append("#endif\n")
                changed += 1
                i += 1
                continue
            out.append(line)
            i += 1
        new = "".join(out)
        if new != original:
            path.write_text(new)
    return changed


def emit_header(decls: OrderedDict) -> None:
    lines = [
        "/* Generated by tools/scripts/gen_battle_overlay_guest_ram.py — do not edit. */",
        "#ifndef XENO_BATTLE_OVERLAY_GUEST_RAM_H",
        "#define XENO_BATTLE_OVERLAY_GUEST_RAM_H",
        "",
        "#include \"types.h\"",
        "",
        "/* Overlay-range D_* live in the loaded battle.bin image. Arrays and",
        " * scalars alias guest RAM. Pointer-typed symbols load the guest word",
        " * and translate that address too. */",
        "",
    ]
    for name, (kind, type_tok) in decls.items():
        addr = overlay_addr(name)
        assert addr is not None
        hex_addr = f"0x{addr:08X}"
        if kind == "ptr":
            lines.append(
                f"#define {name} (({type_tok} *)PSX_ADDR(*(u32 *)PSX_ADDR({hex_addr})))"
            )
        elif kind == "array":
            lines.append(f"#define {name} (({type_tok} *)PSX_ADDR({hex_addr}))")
        else:
            lines.append(f"#define {name} (*(({type_tok} *)PSX_ADDR({hex_addr})))")
    lines += ["", "#endif", ""]
    HEADER.write_text("\n".join(lines))


def adoptable(decls: OrderedDict) -> list[str]:
    mapped = set(decls)
    names = []
    already = {
        "func_80079934",
        "func_80089B50",
        "func_800A3484",
        "func_800AEEEC",
        "func_800B16A4",
        "func_800B6930",
        "func_800B6990",
        "func_800B69E4",
    }
    for path in sorted(BATTLE_SRC.glob("*.c")):
        text = path.read_text(errors="ignore")
        for match in FUNC_RE.finditer(text):
            name = match.group(1)
            body = extract_body(text, match.end() - 1)
            code = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
            code = re.sub(r"//.*", "", code)
            stripped = code.strip()
            if stripped in ("", "return;", "return 0;", "return 0u;"):
                continue
            if NESTED_RE.search(match.group(2) + code):
                continue
            if re.search(r"\*\(\s*u32\s*\*\s*\)\s*\([^)]+\)", code):
                continue
            used = set(re.findall(r"\b(D_\w+)\b", code))
            if any(overlay_addr(n) is not None and n not in mapped for n in used):
                continue
            names.append(name)
    # unique, keep order, include already
    seen = set()
    out = []
    for n in list(already) + names:
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def main() -> None:
    decls = collect_decls()
    emit_header(decls)
    wrapped = wrap_externs(set(decls))
    leaves = adoptable(decls)
    CANDIDATES.write_text("".join(f'    "{n}",\n' for n in leaves))
    print(f"symbols {len(decls)} wrapped-externs {wrapped} candidates {len(leaves)}")
    print(f"wrote {HEADER.relative_to(ROOT)}")
    print(f"wrote {CANDIDATES.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
